config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  
  resources :users 
  resources :categories
  resources :services
  resources :bills
  resources :feed_backs
  resources :rooms do
    resources :bills
  end
  get "/search_user", to: "users#index"
  post "/search_user", to: "users#search"
  get "/search_room", to: "rooms#index"
  post "/search_room", to: "rooms#search_room"
  get "/search_feed_back", to: "feed_backs#index"
  post "/search_feed_back", to: "feed_backs#search_feed_back"
end

app/models/service.rb
class Service < ApplicationRecord
  SERVICE_PARAMS = %i(name price).freeze

  has_many :bill_services
  has_many :bills, through: :bill_services

  scope :ordered_by_number, -> {order name: :asc}
  scope :not_exits_in_bill, -> id_service{where.not(id: id_service)}

  validates :name, presence: true, uniqueness: {case_sensitive: false}
  validates :price, presence: true
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :logged_in_user, except: %i(new create)
  before_action :load_services, except: %i(new create index)
  before_action :admin_user, except: %i(show)

  def index
    @services = Service.page(params[:page]).per(Settings.paging_table).ordered_by_number
  end

  def new
    @service = Service.new
  end

  def create
    @service = Service.new services_params
    if @service.save
      flash[:success] = t "success"
      redirect_to @service
    else
      render :new
    end
  end

  def show; end

  def update
    if @service.update services_params
      flash[:success] = t "success"
      redirect_to services_path
    else
      render :edit
    end
  end

  def destroy
    if @service.destroy
      flash[:success] = t "success"
    else
      flash[:danger] = t "fail"
    end
    redirect_to services_url
  end

  private
  def services_params
    params.require(:service).permit Service::SERVICE_PARAMS
  end

  def load_services
    @service = Service.find_by id: params[:id]
    return if @service
    flash[:danger] = t "fail"
    redirect_to root_path
  end
end

app/views/services/_form.html.erb
<%= form_for @service do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <%= f.label t("name") %>
  <%= f.text_field :name, class: "form-control mb-1" %>
    
  <%= f.label t("price") %>
  <%= f.text_field :price, class: "form-control mb-1", data: {autonumeric: {mDec: Settings.number_zero}} %>
  
  <%= f.submit t("submit"), class: "btn btn-primary" %>
<% end %>

app/views/services/_service.html.erb
<tr>
  <td><span><%= get_index_page service_counter %> </span></td>
  <td><span><%= service.name %></span></td>
  <td><span><%= number_to_vnd service.price %></span></td>
  <td>
    <%= link_to service, title: t("show"), class: "btn btn-info btn-sm" do %>
      <i class="fa fa-eye"></i>
    <% end %>
    <%= link_to edit_service_path(service), title: t("edit"), class: "btn btn-warning btn-sm" do %>
      <i class="fa fa-edit"></i>
    <% end %>
    <%= link_to service, title: t("delete"), method: :delete, data: {confirm: t("sure")}, class: "btn btn-danger btn-sm" do %>
      <i class="fa fa-trash"></i>
    <% end %>
  </td>
</tr>

app/views/services/edit.html.erb
<% provide :title, t("add_service") %>
<h1 class="text-center"><%= t("add_service") %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/services/index.html.erb
<% provide :title, t("room") %>
<div>
<h1><%= t("service") %></h1>
<%= link_to t("add_service"), new_service_path, class: "btn btn-primary" %>
</div>
<div class="row">
  <div class="col-lg-12">
    <div class="main-box no-header clearfix">
      <div class="main-box-body clearfix">
        <div class="table-responsive">
          <table class="table user-list">
            <thead>
              <tr>
              <th><span><%= t("stt") %></span></th>
                <th><span><%= t("name") %></span></th>
                <th><span><%= t("price") %></span></span></th>
                <th><span><%= t("action") %></span></span></th>
              </tr>
            </thead>
              <tbody>
                <%= render partial: "service", collection: @services %>
              </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<%= paginate @services, theme: t("theme_paging") %>

app/views/services/new.html.erb
<% provide :title, t("add_service") %>
<h1 class="text-center"><%= t("add_service") %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/services/show.html.erb
<% provide :title, @service.name %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @service.name %>        
      </h1>
      <p>t("price"): <%= number_to_vnd @service.price %></p>
    </section>
  </aside>
</div>