config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  
  resources :users 
  resources :categories
  resources :services
  resources :bills
  resources :feed_backs
  resources :rooms do
    resources :bills
  end
  get "/search_user", to: "users#index"
  post "/search_user", to: "users#search"
  get "/search_room", to: "rooms#index"
  post "/search_room", to: "rooms#search_room"
  get "/search_feed_back", to: "feed_backs#index"
  post "/search_feed_back", to: "feed_backs#search_feed_back"
end

app/models/room.rb
class Room < ApplicationRecord
  ROOM_PARAMS = %i(name category_id status payment).freeze
  enum status: {active: 1, unactive: 0}
  enum payment: {paymented: 1, unpayment: 0}
  after_create :update_price

  belongs_to :category
  has_many :user, dependent: :nullify
  has_many :bill

  scope :ordered_by_id, -> {order(id: :asc)}
  scope :find_by_status_room, -> status {where(status: status)}

  delegate :name, to: :category, prefix: true
  delegate :price, to: :category, prefix: true
  delegate :name, to: :user, prefix: true

  validates :name, presence: true

  def update_price
    update price: self.category.price
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :logged_in_user, except: %i(new create)
  before_action :load_room, except: %i(new create index search_room)
  before_action :admin_user, except: %i(show index search_room)
  before_action :load_rooms, only: %i(index search_room)
  
  def index; end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new room_params
    if @room.save
      flash[:success] = t "success"
      redirect_to @room
    else
      render :new 
    end
  end

  def edit; end

  def update
    if @room.update room_params
      flash[:success] = t "success"
      redirect_to @room
    else
      render :edit
    end
  end

  def show; end

  def destroy
    if @room.destroy
      flash[:success] = t "success"
    else
      flash[:danger] = t "fail"
    end
    redirect_to rooms_url
  end

  def search_room
    respond_to do |format|
      format.html
      format.js
    end
  end

  private
  def room_params
    params.require(:room).permit Room::ROOM_PARAMS
  end

  def load_room
    @room = Room.find_by id: params[:id]
    return if @room
    flash[:danger] = t "fail"
    redirect_to root_path
  end

  def load_rooms
    @rooms = Room.where nil
    @rooms = @rooms.find_by_status_room(params[:status]) if params[:status].present?
    @rooms = @rooms.page(params[:page]).per(Settings.paging_table_room).ordered_by_id
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
  def get_category
    Category.pluck :name, :id
  end
end

app/views/rooms/_form.html.erb
<%= form_for @room do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.label t("name") %>
  <%= f.text_field :name, class: "form-control mb-1" %>

  <%= f.label t("category") %>
  <%= f.select :category_id, get_category, {include_blank: t("category")}, {class: "form-control"} %>

  <%= f.label t("status") %><br/>
  <%= f.radio_button :status, :active, checked: "checked" %> <%= t("active") %> <br/>
  <%= f.radio_button :status, :unactive %> <%= t("unactive") %><br/> 

  <%= f.hidden_field :payment, value: "unpayment", class: "form-control mb-1" %>  

  <%= f.submit t("submit"), class: "btn btn-primary mt-1" %>
<% end %>

app/views/rooms/_list_room.html.erb
<div class="row order">
  <% @rooms.each do |room| %>
    <div id="table-a" class="col-xs-4 col-sm-3 col-md-2">
      <div>
        <i class="fa fa-home">
        <div class= "action_room">
          <%= link_to room, title: t("show"), class: "btn btn-info btn-sm" do %>
            <i class="fa fa-eye"></i>
          <% end %>
          <%= link_to edit_room_path(room), title: t("edit"), class: "btn btn-warning btn-sm" do %>
            <i class="fa fa-edit"></i>
          <% end %>
          <%= link_to room, title: t("delete"), method: :delete, data: {confirm: t("sure")}, class: "btn btn-danger btn-sm" do %>
            <i class="fa fa-trash"></i>
          <% end %>
        </div> 
        </i>        
      </div>
      <%= link_to room_path room.id do %>
        <% if room.active? %>
          <div class="tables text-center" id="room-active">
            <div class="status">
              <div class="status-table">
                <p class="text-center"><%= room.name %></p>
              </div>
            </div>               
          <p class="status_1"><%= t("status") %>: <%= room.status %> </p> 
          <% if room.paymented? %>
            <p class="paymented"><%= t("paymented") %></p>
          <% else  %>
          <span class="unpayment"><%= t("unpayment") %></span>
          <% end %>   
          </div>
        <% else %>
          <div class="tables text-center">
            <div class="status">
              <div class="status-table">
                <p class="text-center"><%= room.name %></p>
              </div>
            </div>           
          <p class="status_1"> status: <%= room.status %> </p>          
          </div>
        <% end %> 
      <% end %>  
    </div>
  <% end %>
</div>
<%= paginate @rooms, theme: t("theme_paging") %>

app/views/rooms/_room.html.erb
<tr>
  <td><span><%= room.name %></span></td>
  <td><span><%= room.category_name %></span></td>
  <td><span><%= room.status %></span></td> 
  <td>
    <%= link_to t(".delete"), room, method: :delete,
  data: { confirm: t("sure") } %> | 
  <%= link_to t(".show"), room %> |
  <%= link_to t(".edit"), edit_room_path(room) %>
  </td>
</tr>

app/views/rooms/edit.html.erb
<% provide :title, t("edit_room") %>
<h1 class="text-center"><%= t("edit_room") %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/rooms/index.html.erb
<% provide :title, t("room") %>
<div>
  <h1><%= t("room") %></h1>
</div>

<div class= "col-lg-12">
  <div class="col-lg-6"> 
    <%= link_to t("add_room"), new_room_path, class: "btn btn-primary" %>
  </div>
  <div class="col-lg-6">
    <div class="col-lg-6" id="search_ip">
    <%= select_tag :status, options_for_select(enum_options_for_select(Room, :status).insert(0, t("search"))), class: "form-control", id: "find_by_status_room" %>
    </div>
  </div>
</div>

<div id= "list_room">
  <%= render "rooms/list_room" %>  
</div>

app/views/rooms/index.js.erb
$('#list_room').html('<%= j render 'rooms/list_room', rooms: @rooms %>');
$('#paginator').html('<%= j paginate(@rooms, remote: true) %>');

app/views/rooms/new.html.erb
<% provide :title, t("add_room") %>
<h1 class="text-center"><%= t("add_room") %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/rooms/search_room.js.erb
$('#list_room').html('<%= j render 'rooms/list_room', rooms: @rooms %>');

app/views/rooms/show.html.erb
<% provide :title, @room.name %>
<div class="row">
<% if @room.active?  %> 
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @room.name %>
      </h1>
      <p><%= t("category") %>: <%= @room.category_name %></p>
      <p><%= t("price") %>: <%= number_to_vnd @room.category_price %></p>

      <p><%= t("name_room") %>: <%= @room.name %></p>
    </section>
    <% if @room.unpayment? && current_user.manager?  %> 
      <%= link_to t("create_bill"), new_room_bill_path(@room.id), class: "btn btn-primary" %>
    <% end %>
    <%= link_to t("view_bill"), room_bills_path(@room), class: "btn btn-primary" %>
  </aside>
  <% else %>
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @room.name %>
      </h1>
      <p><%= t("category") %>: <%= @room.category_name %></p>
      <p><%= t("price") %>: <%= number_to_vnd @room.category_price %></p>
      <%= link_to t("add_user"), new_user_path, class: "btn btn-primary" %>
    </section>
  </aside>
  <% end %>
</div>