config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  
  resources :users 
  resources :categories
  resources :services
  resources :bills
  resources :feed_backs
  resources :rooms do
    resources :bills
  end
  get "/search_user", to: "users#index"
  post "/search_user", to: "users#search"
  get "/search_room", to: "rooms#index"
  post "/search_room", to: "rooms#search_room"
  get "/search_feed_back", to: "feed_backs#index"
  post "/search_feed_back", to: "feed_backs#search_feed_back"
end

app/models/category.rb
class Category < ApplicationRecord
  CATEGORY_PARAMS = %i(name price).freeze
  
  has_many :rooms, dependent: :destroy

  scope :ordered_by_number, -> {order name: :asc}

  validates :name, presence: true, uniqueness: {case_sensitive: false}
  validates :price, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :logged_in_user
  before_action :load_category, except: %i(new create index)
  before_action :admin_user, except: %i(show)

  def index
    @categorys = Category.page(params[:page]).per(Settings.paging_table).ordered_by_number
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = t "success"
      redirect_to @category
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @category.update category_params
      flash[:success] =  t "success"
      redirect_to categories_path
    else
      render :edit
    end
  end

  def destroy
    if @category.destroy
      flash[:success] = t "success"
    else
      flash[:danger] = t "fail"
    end
    redirect_to categories_url
  end

  private
  def category_params
    params.require(:category).permit Category::CATEGORY_PARAMS
  end

  def load_category
    @category = Category.find_by id: params[:id]
    return if @category
    flash[:danger] = t "not_exist"
    redirect_to root_path
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<tr>
  <td><span><%= get_index_page category_counter %></span></td>
  <td><span><%= category.name %></span></td>
  <td><span><%= number_to_vnd category.price %></span></td>
  <td>
    <%= link_to category, title: t("show"), class: "btn btn-info btn-sm" do %>
      <i class="fa fa-eye"></i>
    <% end %>
    <%= link_to edit_category_path(category), title: t("edit"), class: "btn btn-warning btn-sm" do %>
      <i class="fa fa-edit"></i>
    <% end %>
    <%= link_to category, title: t("delete"), method: :delete, data: {confirm: t("sure")}, class: "btn btn-danger btn-sm" do %>
      <i class="fa fa-trash"></i>
    <% end %>
  </td>
</tr>

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <%= f.label t("name") %>
  <%= f.text_field :name, class: "form-control mb-1" %>
  
  <%= f.label t("price") %>
  <%= f.text_field :price, class: "form-control mb-1", data: {autonumeric: {mDec: Settings.number_zero}} %>

  <%= f.submit t("submit"), class: "btn btn-primary" %>
<% end %>

app/views/categories/edit.html.erb
<% provide :title, t("edit_category") %>
<h1 class="text-center"> <%= t("edit_category") %> </h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/categories/index.html.erb
<% provide :title, "Category" %>
<div>
<h1><%= t("category") %></h1>
<%= link_to t("add_category"), new_category_path,  class: "btn btn-primary" %>
</div>

<div class="row">
  <div class="col-lg-12">
    <div class="main-box no-header clearfix">
      <div class="main-box-body clearfix">
        <div class="table-responsive">
          <table class="table user-list">
            <thead>
              <tr>
                <th><span><%= t("name") %></span></th>
                <th><span><%= t("price") %></span></th>
                <th><span><%= t("action") %></th>
              </tr>
            </thead>
              <tbody>
                <%= render partial: "category", collection: @categorys %>
              </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<%= paginate @categorys, theme: t("theme_paging") %>

app/views/categories/new.html.erb
<% provide :title, t("add_category") %>
<h1 class="text-center"><%= t("add_category") %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/categories/show.html.erb
<% provide :title, @category.name %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @category.name%>
      </h1>
      <p><%= t("price") %>: <%= number_to_vnd @category.price%></p>
    </section>
  </aside>
</div>