config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  
  resources :users 
  resources :categories
  resources :services
  resources :bills
  resources :feed_backs
  resources :rooms do
    resources :bills
  end
  get "/search_user", to: "users#index"
  post "/search_user", to: "users#search"
  get "/search_room", to: "rooms#index"
  post "/search_room", to: "rooms#search_room"
  get "/search_feed_back", to: "feed_backs#index"
  post "/search_feed_back", to: "feed_backs#search_feed_back"
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <p class="center">
    <%= t "design_by" %> 
  </p>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("tittle_website"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= t("language") %> <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to t("vietnamese"), locale:"vi" %></li>
            <li><%= link_to t("english"), locale:"en" %></li>
          </ul>
        </li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.name %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to t(".logout"), logout_path, method: :delete %>
              </li>
              <li>
                <%= link_to t("profile"), current_user%>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("login"), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<nav id="sidebar">
  <button  type="button" id="sidebarCollapse" class="btn btn-info">
      <i class="fa fa-bars"></i>      
  </button>
  <div class="sidebar-header text-center">
    <h3><%= t "dashboard" %></h3>
  </div>

  <% if current_user.manager? %>
    <ul class="list-unstyled components">
      <li>
        <%= link_to t("categorys"), categories_path %>
      </li>
      <li>
          <%= link_to t("rooms"), rooms_path %>
      </li>
      <li>
        <%= link_to t("users"), users_path %>
      </li>
      <li>
        <%= link_to t("service"), services_path %>
      </li>
      <li>
        <%= link_to t("feed_back"), feed_backs_path %>
      </li>
    </ul>
  <% else %>
    <ul class="list-unstyled components">
      <li>
        <%= link_to t("rooms"), rooms_path %>
      </li>
      <li>
        <%= link_to t("feed_back"), feed_backs_path %>
      </li>
    </ul>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield(:title)%></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <%= render "layouts/shim" %>
  </head>

  <body>
    <div class="wrapper" id="side-bar">
      <%= render "layouts/header" %>
      <% if logged_in?%>
        <%= render "layouts/sidebar" %>
      <% end %>
      <div class="container main-page" >
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
        <%= yield %>
      </div>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield(:title)%></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <%= render "layouts/shim" %>
  </head>

  <body>
    <div class="wrapper" id="side-bar">
      <%= render "layouts/header" %>
      <% if logged_in?%>
        <%= render "layouts/sidebar" %>
      <% end %>
      <div class="container main-page" >
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
        <%= yield %>
      </div>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>